### ISSUE TITLE
Cannot update 'is_deleted'

### ISSUE THREAD

**Issue by scrnjakovic** [developerworks/hierarchy-data-closure-table#5]
Trying to update any nodes 'is_deleted' gives following error:

```
1442 - Can't update table 'prefix_nodes' in stored function/trigger because it is already used by statement which invoked this stored function/trigger. 
```

Updating the table from an update trigger would then cause the same trigger to fire again in an infinite recursive loop. This is why this feature should either be removed, or I'm missing something.

**Comment by vahidalvandi** [comment]
how i use recursive function for update is_delete???

**Comment by benfavre** [comment]
You don't ever touch that field directly because it will be managed by triggers.
You could re-write the whole code from this repo to use "triggers/events" in your code and then you could have a case where you could bypass the triggers and update the fields manually.

**Comment by vahidalvandi** [comment]
i need update is_deleted from update query i set triggers and procedures but print error 

#1442 - Can't update table 'webineh_prefix_nodes' in stored function/trigger because it is already used by statement which invoked this stored function/trigger.


please help me how i change is_set to 1 and how i use move procedure


very very thanks
